export default {
  squareSize: 10,
  squarePadding: 1,
  startOfWeek: 1 as 0 | 1 | 2 | 3 | 4 | 5 | 6,
  daysInWeek: 7,
  weekLabels: ["Mon", "", "Wed", "", "Fri", "", "Sun"],
  monthLabels: [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ],
};
